name: check
on: 
  pull_request:
   types: [opened, reopened, synchronize, edited]

jobs:
   job1:
      name: check
      runs-on: ubuntu-latest
      steps:
       - uses: Slashgear/action-check-pr-title@v4.3.0
         with:
           regexp: '^ACDEV-\d{4} .+$' # Regex the title should match
